AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Resources:

  FlashcardGenerator:
    Type: AWS::Serverless::Function

    Properties:

      Runtime: go1.x
      Handler: generateFlashcard

      Architectures:
        - x86_64

      CodeUri: generators/

      Timeout: 5
      Environment:
        Variables:
          GEMINI_API_KEY: ""

      Events:

        Api:
          Type: Api
          Properties:
            Path: /flashcard-generator
            Method: get